tabs -> spaces

diff --git a/bin/yarcurl b/bin/yarcurl
--- a/bin/yarcurl
+++ b/bin/yarcurl
@@ -7,29 +7,29 @@
 #-------------------------------------------------------------------------------
 
 usage() {
-	echo "usage: `basename $0` [-v] [GET|POST|PUT|DELETE] <uri>"
+    echo "usage: `basename $0` [-v] [GET|POST|PUT|DELETE] <uri>"
 }
 
 VERBOSE=0
 if [ 2 -lt $# ]; then
-	if [ "-v" == $1 ]; then
-		VERBOSE=1
-		shift
-	fi
+    if [ "-v" == $1 ]; then
+        VERBOSE=1
+        shift
+    fi
 fi
 
 if [ $# != 2 ]; then
-	usage
-	exit 1
+    usage
+    exit 1
 fi
 
 if [ "$YAR_CREDS" == "" ]; then
-	YAR_CREDS=~/.yar.creds
+    YAR_CREDS=~/.yar.creds
 fi
 
 if [ ! -f $YAR_CREDS ]; then
-	echo "`basename $0`: can't read from creds file '$YAR_CREDS'"
-	exit 1
+    echo "`basename $0`: can't read from creds file '$YAR_CREDS'"
+    exit 1
 fi
 
 SCRIPTDIR="$( cd "$( dirname "$0" )" && pwd )"
@@ -37,17 +37,17 @@ SCRIPTDIR="$( cd "$( dirname "$0" )" && pwd )"
 HTTP_METHOD=`echo $1 | awk '{print toupper($0)}'`
 case "$HTTP_METHOD" in
         GET|DELETE)
-			CONTENT_TYPE=""
-			COPY_OF_STDIN=/dev/null
+            CONTENT_TYPE=""
+            COPY_OF_STDIN=/dev/null
             ;;
         PUT|POST)
-			CONTENT_TYPE="application/json; charset=utf-8"
-			COPY_OF_STDIN=`mktemp`
-			cat /dev/stdin > $COPY_OF_STDIN
+            CONTENT_TYPE="application/json; charset=utf-8"
+            COPY_OF_STDIN=`mktemp`
+            cat /dev/stdin > $COPY_OF_STDIN
             ;;
         *)
             usage
-			exit 1
+            exit 1
 esac
 
 get_creds() {
@@ -56,22 +56,22 @@ get_creds() {
 
 MAC_KEY_IDENTIFIER=`get_creds MAC_KEY_IDENTIFIER`
 if [ "$MAC_KEY_IDENTIFIER" == "" ]; then
-	echo "`basename $0` could not find mac key identifier"
-	exit 1
+    echo "`basename $0` could not find mac key identifier"
+    exit 1
 fi
 
 MAC_KEY=`get_creds MAC_KEY`
 if [ "$MAC_KEY" == "" ]; then
-	echo "`basename $0` could not find mac key"
-	exit 1
+    echo "`basename $0` could not find mac key"
+    exit 1
 fi
 MAC_KEY=$(echo -n $MAC_KEY | sed -e "s/\-/\+/g" | sed -e "s/\_/\//g")=
 MAC_KEY=$(echo -n $MAC_KEY | base64 --decode)
 
 MAC_ALGORITHM=`get_creds MAC_ALGORITHM`
 if [ "$MAC_ALGORITHM" == "" ]; then
-	echo "`basename $0` could not find mac algorithm"
-	exit 1
+    echo "`basename $0` could not find mac algorithm"
+    exit 1
 fi
 
 URL=$(echo $2 | sed -e "s/^\\s*//")
@@ -90,74 +90,74 @@ TIMESTAMP=$(date +%s)
 NONCE=$(openssl rand -hex 16)
 
 get_ext() {
-	CONTENT_TYPE=${1:-}
-	COPY_OF_STDIN=${2:-}
-	if [ "$CONTENT_TYPE" == "" ] || [ "$COPY_OF_STDIN" == "" ]; then
-		echo ""
-	else
-		CONTENT_TYPE_PLUS_COPY_OF_STDIN=`mktemp`
-		echo -n $CONTENT_TYPE > $CONTENT_TYPE_PLUS_COPY_OF_STDIN
-		cat $COPY_OF_STDIN >> $CONTENT_TYPE_PLUS_COPY_OF_STDIN
-		openssl sha1 < $CONTENT_TYPE_PLUS_COPY_OF_STDIN
-		rm $CONTENT_TYPE_PLUS_COPY_OF_STDIN
-	fi
+    CONTENT_TYPE=${1:-}
+    COPY_OF_STDIN=${2:-}
+    if [ "$CONTENT_TYPE" == "" ] || [ "$COPY_OF_STDIN" == "" ]; then
+        echo ""
+    else
+        CONTENT_TYPE_PLUS_COPY_OF_STDIN=`mktemp`
+        echo -n $CONTENT_TYPE > $CONTENT_TYPE_PLUS_COPY_OF_STDIN
+        cat $COPY_OF_STDIN >> $CONTENT_TYPE_PLUS_COPY_OF_STDIN
+        openssl sha1 < $CONTENT_TYPE_PLUS_COPY_OF_STDIN
+        rm $CONTENT_TYPE_PLUS_COPY_OF_STDIN
+    fi
 }
 EXT=$(get_ext "$CONTENT_TYPE" "$COPY_OF_STDIN")
 
 NRS=`mktemp`
 printf \
-	'%s\n%s\n%s\n%s\n%s\n%s\n%s\n' \
-	$TIMESTAMP \
-	$NONCE \
-	$HTTP_METHOD \
-	$URI \
-	$HOST \
-	$PORT \
-	$EXT >& $NRS
+    '%s\n%s\n%s\n%s\n%s\n%s\n%s\n' \
+    $TIMESTAMP \
+    $NONCE \
+    $HTTP_METHOD \
+    $URI \
+    $HOST \
+    $PORT \
+    $EXT >& $NRS
 MAC=$(openssl dgst -sha1 -hmac "$MAC_KEY" < $NRS | sed -e "s/^.*=\s*//g")
 rm -f $NRS >& /dev/null
 
 printf \
-	-v AUTH_HEADER_VALUE \
-	'MAC id=\"%s\", ts=\"%s\", nonce=\"%s\", ext=\"%s\", mac=\"%s\"' \
-	"$MAC_KEY_IDENTIFIER" \
-	"$TIMESTAMP" \
-	"$NONCE" \
-	"$EXT" \
-	"$MAC"
+    -v AUTH_HEADER_VALUE \
+    'MAC id=\"%s\", ts=\"%s\", nonce=\"%s\", ext=\"%s\", mac=\"%s\"' \
+    "$MAC_KEY_IDENTIFIER" \
+    "$TIMESTAMP" \
+    "$NONCE" \
+    "$EXT" \
+    "$MAC"
 
 if [ $VERBOSE -eq 1 ]; then
-	CURL_VERBOSE=-v
+    CURL_VERBOSE=-v
 else
-	CURL_VERBOSE=""
+    CURL_VERBOSE=""
 fi
 
 if [ "" != "$CONTENT_TYPE" ]; then
-	CURL_CMD="curl
-		-s
-		$CURL_VERBOSE
-		-X $HTTP_METHOD
-		-H \"Authorization: \$AUTH_HEADER_VALUE\"
-		-H \"Content-Type: $CONTENT_TYPE\"
-		--data-binary @$COPY_OF_STDIN
-	   $URL"
+    CURL_CMD="curl
+        -s
+        $CURL_VERBOSE
+        -X $HTTP_METHOD
+        -H \"Authorization: \$AUTH_HEADER_VALUE\"
+        -H \"Content-Type: $CONTENT_TYPE\"
+        --data-binary @$COPY_OF_STDIN
+       $URL"
 else
-	CURL_CMD="curl
-		-s
-		$CURL_VERBOSE
-		-X $HTTP_METHOD
-		-H \"Authorization: \$AUTH_HEADER_VALUE\"
-	   $URL"
+    CURL_CMD="curl
+        -s
+        $CURL_VERBOSE
+        -X $HTTP_METHOD
+        -H \"Authorization: \$AUTH_HEADER_VALUE\"
+       $URL"
 fi
 
 # if [ $VERBOSE -eq 1 ]; then
-#	echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
-#	eval echo $CURL_CMD
-#	echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
+#    echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
+#    eval echo $CURL_CMD
+#    echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
 # fi
 
 # if [ $VERBOSE -eq 1 ]; then
-# 	set -x verbose
+#     set -x verbose
 # fi
 # eval $CURL_CMD > ~/ooo 2>&1
 
